### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 484375) of binary

### ISSUE THREAD

**Issue by Cooperx521** [RLHF-V/RLHF-V#11]
Hello~ I have used 8 A100 and almost didn't change anything, but encountered this problem. Could you help to have a look? I have set `GPUS_PER_NODE=8`, and command line is `srun --partition=llm3 --gres=gpu:8 --nodes=1 --cpus-per-task=16 --job-name=RLHF-V --ntasks-per-node=8 bash run_RLHFV.sh`
![image](https://github.com/RLHF-V/RLHF-V/assets/131770126/4e1ef357-6992-4944-a7db-df94971e02fe)

detailed information:

```

> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484376 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484378 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484379 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484380 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484381 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484383 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484384 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 484375) of binary: /mnt/petrelfs/xinglong/anaconda3/envs/muffin/bin/python
> Traceback (most recent call last):
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/bin/torchrun", line 33, in <module>
>     sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> =======================================================
> ./muffin/train/train_mem_muffin.py FAILED
> -------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> -------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2024-01-30_11:52:52
>   host      : SH-IDC1-10-140-1-167
>   rank      : 0 (local_rank: 0)
>   exitcode  : -9 (pid: 484375)
>   error_file: <N/A>
>   traceback : Signal 9 (SIGKILL) received by PID 484375
> =======================================================
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484385 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484389 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484391 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484395 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484397 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484398 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 484399 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 484387) of binary: /mnt/petrelfs/xinglong/anaconda3/envs/muffin/bin/python
> Traceback (most recent call last):
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/bin/torchrun", line 33, in <module>
>     sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/mnt/petrelfs/xinglong/anaconda3/envs/muffin/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> =======================================================
> ./muffin/train/train_mem_muffin.py FAILED
> -------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> -------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2024-01-30_11:53:13
>   host      : SH-IDC1-10-140-1-167
>   rank      : 1 (local_rank: 1)
>   exitcode  : -9 (pid: 484387)
>   error_file: <N/A>
>   traceback : Signal 9 (SIGKILL) received by PID 484387
> =======================================================

```

**Comment by Menoly-xin** [comment]
I have met the same issue. The error message is exactly the same.

**Comment by Menoly-xin** [comment]
This error happens when loading the pre-trained model. Have you solved this problem?

**Comment by Cooperx521** [comment]
> This error happens when loading the pre-trained model. Have you solved this problem?

No, I have tried a lot, but it remains the same. If you solve it, could you please let me know?

**Comment by Menoly-xin** [comment]
> > This error happens when loading the pre-trained model. Have you solved this problem?
> 
> No, I have tried a lot, but it remains the same. If you solve it, could you please let me know?

Not yet. It may be related to the python env.

**Comment by yiranyyu** [comment]
> This error happens when loading the pre-trained model. Have you solved this problem?

This error message might be printed when encountering the OOM problem. Loading the model in our currently implementation causes a temporarily memory consumption peak.
