### ISSUE TITLE
KeyError: <InterpolationMode.BICUBIC: 'bicubic'>

### ISSUE THREAD

**Issue by nicochen1118** [RLHF-V/RLHF-V#23]
Some weights of Beit3LlavaLlamaForCausalLM were not initialized from the model checkpoint at ./RLHF-V_SFT_weight and are newly initialized: ['model.vision_tower.beit3.vision_embed.mask_token', 'model.vision_tower.beit3.text_embed.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Update vision arch from beit3_large_patch16_672 to beit3_large_patch16_448
Position interpolate from 42x42 to 28x28
Traceback (most recent call last):
  File "/home/nfs03/xingsy/RLHF-V/muffin/./muffin/train/train_mem_muffin.py", line 13, in <module>
    train()
  File "/home/nfs03/xingsy/RLHF-V/muffin/muffin/train/train_muffin.py", line 465, in train
    model, data_module, tokenizer = init_model(model_args, data_args, training_args)
  File "/home/nfs03/xingsy/RLHF-V/muffin/muffin/train/train_muffin.py", line 353, in init_model
    model_vision_dict = model.model.initialize_vision_modules(
  File "/home/nfs03/xingsy/RLHF-V/muffin/muffin/model/muffin.py", line 181, in initialize_vision_modules
    train_img_transform, eval_img_transform = build_transform(
  File "/home/nfs03/xingsy/RLHF-V/muffin/muffin/model/utils.py", line 413, in build_transform
    RandomResizedCropAndInterpolation(
  File "/home/nfs04/xingsy/tf41py310/lib/python3.10/site-packages/timm/data/transforms.py", line 126, in __init__
    self.interpolation = str_to_interp_mode(interpolation)
  File "/home/nfs04/xingsy/tf41py310/lib/python3.10/site-packages/timm/data/transforms.py", line 84, in str_to_interp_mode
    return _str_to_torch_interpolation[mode_str]
KeyError: <InterpolationMode.BICUBIC: 'bicubic'>

**Comment by Haoye17** [comment]
Hi @nicochen1118, thank you for your interest in our work!

This error may occur with an incompatible timm or transformers version, could you check out if your package versions meet our requirements? If the error still occurs, could you provide more information about your environment setting to help us reproduce the error? We will do our best to help ~

**Comment by nicochen1118** [comment]
Thanks！
