### ISSUE TITLE
ImportError: cannot import name 'flash_attn_unpadded_qkvpacked_func' from 'flash_attn.flash_attn_interface'

### ISSUE THREAD

**Issue by linhaojia13** [RLHF-V/RLHF-V#7]
I follow the ReadMe to install the environment an then run `muffin/script/train/run_RLHFV.sh` but it returns the ImportError:
```
Traceback (most recent call last):
  File "~/codes_MLLM/RLHF-V/muffin/./muffin/train/train_mem_muffin.py", line 6, in <module>
    from muffin.train.llama_flash_attn_monkey_patch import replace_llama_attn_with_flash_attn
  File "~/codes_MLLM/RLHF-V/muffin/muffin/train/llama_flash_attn_monkey_patch.py", line 12, in <module>
    from flash_attn.flash_attn_interface import flash_attn_unpadded_qkvpacked_func
ImportError: cannot import name 'flash_attn_unpadded_qkvpacked_func' from 'flash_attn.flash_attn_interface' (~/miniconda3/envs/muffin/lib/python3.10/site-packages/flash_attn-2.4.2-py3.10-linux-x86_64.egg/flash_attn/flash_attn_interface.py)
```

**Comment by linhaojia13** [comment]
`flash_attn_unpadded_qkvpacked_func -> flash_attn_varlen_qkvpacked_func`
Making such change will solve this problem.
